#!/bin/sh
cat README
echo "----------------------------------------------"

for i in *;
do
	if [ -x $i ];then
		if [ "x$i" == "xautotest" ] ;then continue; fi
		printf "\033[1;1m===> Run $i ... \033[1;0m\n" >&2
		case $i in
			*)
			time ./$i 
			;;
		esac
	fi
done
