#!/bin/sh

echo "-----求小于1000的，能被3或5整除的，正整数之和-----"

for i in *;
do
	if [ -x $i ];then
		if [ "x$i" == "xautotest" ] ;then continue; fi
		printf "\033[1;1m===> Run $i ... \033[1;0m\n" >&2
		case $i in
			*toupar)
			./$i 1000
			;;

			*)
			./$i 
			;;
		esac
	fi
done
