#!/bin/sh
num1=`expr $RANDOM % 1000`
num2=`expr $RANDOM % 1000`

echo "-----计算 $num1 和 $num2 的最大公约数-----"

for i in `ls *|ls |grep -v "~$"`;
do
	if [ -x $i ];then
		if [ "x$i" == "xautotest" ] ;then continue; fi
		echo "=> Run $i ..."
		case $i in
			*jyf|*lerosua|*shan|*twig|*wind)
			echo $num1 $num2 | time ./$i 
			;;
			*)
			time ./$i $num1 $num2
			;;
		esac
	fi
done
