#!/bin/sh
num1=`expr $RANDOM % 10000`
num2=`expr $RANDOM % 14 + 10`
num3=`expr $RANDOM % 34 + 2`

echo "-----计算 $num2 进制数 $num1 转换成 $num3 进制数是多少-----"

for i in *;
do
	if [ -x $i ];then
		if [ "x$i" == "xautotest" ] ;then continue; fi
		echo "=> Run $i ..."
		./$i $num1 $num2 $num3
	fi
done
