#!/bin/sh

echo "-----计算出下面100个50位的数字的和的前十个数字-----"

for i in *;
do
	if [ -x $i ];then
		if [ "x$i" == "xautotest" ] ;then continue; fi
		printf "\033[1;1m===> Run $i ... \033[1;0m\n" >&2
		case $i in
			*toupar)
			./$i 1000
			;;

			*)
			./$i 
			;;
		esac
	fi
done
